### PR TITLE
Add Variables for OEM Output

### PR DESCRIPTION
**Pull request by zwiebo**

### CODE REVIEW

**Comment by zwiebo** [comment]
How do split a PR into several smaller ones?

**Comment by danielhuppmann** [comment]
Just realized that you committed your changes to `zwiebo:main` - one should always work with branches to avoid the quagmire that you’re in now…

The `main` branch on your fork should always follow (be in sync) with `netzero2040:main`.

How to fix it…
- Create a new branch `dev` (to have a copy of all your changes 
- Reset `zwiebo:main` to `netzero2040:main`
- Create a new branch with a descriptive name for a limited set of changes (eg only the new scenario names)
- Commit the particular changes to the branch
- Push the branch to your fork on GitHub
- Start a PR for that branch
- Checkout the `main` branch
- Repeat from „Create a new branch…“

**Comment by zwiebo** [comment]
Ok, thanks. Will do tomorrow.

**Comment by danielhuppmann** [comment]
@zwiebo, any updates?

**Comment by zwiebo** [comment]
> @zwiebo, any updates?
Took some time until I understood. Especially how i can do this. I hope my new PR is ok.

**Pull request closed without merging**
