### PR TITLE
adds gross domestic consumption and corresponding tag

### PR DESCRIPTION
**Pull request by sebwehrle**
I created a new tag with energy carriers. Alternatively, we might add new energy carriers, such as "ambient heat" to an existing tag. However, to me, it seemed as if none of the existing tags would really fit.

### CODE REVIEW

**Review by danielhuppmann — CHANGES_REQUESTED** [review]
You don't need to create a new tag list for your situation, you can simply add two variables: one for an existing tag list, plus an explicit variable, e.g.
```yaml
- Gross Domestic Consumption|{Final Energy Carrier}:
     description: gross domestic consumption of {Final Energy Carrier}
     unit: TJ
- Gross Domestic Consumption|Ambient Heat:
     description: gross domestic consumption of ambient heat (via heat pumps)
     unit: TJ

**Comment by danielhuppmann** [comment]
Also, this "Gross Domestic Consumption" tag is a duplicate of the already-existing "Final Energy|{Final Energy Carrier}" variable.

**Review by zwiebo — APPROVED** [review]

**Comment by danielhuppmann** [comment]
> Final Energy and Gross Domestic Consumption are apparently different things (according to my understanding of aea expert opinion)

Can you or @zwiebo please explain the difference between final-energy consumption and gross domestic consumption of an energy carrier?

**Comment by sebwehrle** [comment]
According to my limited understanding, gross domestic consumption equals final energy plus transmission losses plus energy industry own use plus conversion losses plus statsical differences

**Comment by danielhuppmann** [comment]
Could you please provide a description that explains how this is different from 

https://github.com/netzero2040/netzero2040/blob/6bd34bbb0e82a47c62b5ce0b03ccc7e05b7293ac/definitions/variable/energy.yaml#L49

**Comment by danielhuppmann** [comment]
Closing in favor of #48

**Pull request closed without merging**
